title:  VidyaRekha
tagline:   First step to million





menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}


social:
- {icon: 'github', link: 'https://www.github.com/psphanindra'}

- {icon: 'linkedin', link: 'https://www.linkedin.com/in/phanindrakumarpulletikurti/'}

